export const POST_LIST_REQUEST = "POST_LIST_REQUEST";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";
export const POST_LIST_FAIL = "POST_LIST_FAIL";

export const POST_DETAILS_REQUEST = "POST_DETAILS_REQUEST";
export const POST_DETAILS_SUCCESS = "POST_DETAILS_SUCCESS";
export const POST_DETAILS_FAIL = "POST_DETAILS_FAIL";

// export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
// export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
// export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";

// export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
// export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
// export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";
// export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";

// export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
// export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
// export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";
// export const PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET";

// export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUCT_CREATE_REVIEW_REQUEST";
// export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
// export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCT_CREATE_REVIEW_FAIL";
// export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";
