export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SECCESS = "USER_LOGIN_SECCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_LOGOUT = "USER_LOGIN_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SECCESS = "USER_REGISTER_SECCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SECCESS = "USER_DETAILS_SECCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SECCESS = "USER_UPDATE_SECCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";

// export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
// export const USER_LIST_SECCESS = "USER_LIST_SECCESS";
// export const USER_LIST_FAIL = "USER_LIST_FAIL";
// export const USER_LIST_RESET = "USER_LIST_RESET";

// export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
// export const USER_DELETE_SECCESS = "USER_DELETE_SECCESS";
// export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

// export const USER_UPDATE_ADMIN_REQUEST = "USER_UPDATE_ADMIN_REQUEST";
// export const USER_UPDATE_ADMIN_SECCESS = "USER_UPDATE_ADMIN_SECCESS";
// export const USER_UPDATE_ADMIN_FAIL = "USER_UPDATE_ADMIN_FAIL";
// export const USER_UPDATE_ADMIN_RESET = "USER_UPDATE_ADMIN_RESET";
